apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamfinity-api
  namespace: streamfinity-api
spec:
  replicas: 2
  securityContext:
    runAsUser: 10500
  selector:
    matchLabels:
      app: streamfinity-api
  template:
    metadata:
      labels:
        app: streamfinity-api
    spec:
      containers:
        - name: streamfinity-api
          image: streamfinity-api:v1.0.0-beta
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                -ALL
            runAsUser: 11000
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
          ports:
            - containerPort: 8000

    
