kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: intra-namespace-streamfinity
  namespace: streamfinity-api
spec:
  podSelector:
  matchLabels:
      app: streamfinity-api
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress: []
