name: tflint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v3
    - name: Show version
      run: tflint --version
    - name: Init TFLint
      run: tflint --init
    - name: Run TFLint
      working-directory: ./infra
      run: tflint -f compact
      
      
