name: tfsec

on:
  push:
    branches: ['main']
    paths: ['infra/**']
  pull_request:
    branches: ['main']
    paths: ['infra/**']
      
jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          additional_args: '--concise-output --exclude-downloaded-modules'
